feat: add shadcn sidebar
pubpub/platform pull request #752
Opened 2024-11-05 14:17 UTC by tefkah

- **feat: add sidebar components**
- **feat: rework sidenav to use new sidebar component**
- **chore: format**

## Issue(s) Resolved

## High-level Explanation of PR

## Test Plan

## Screenshots (if applicable)

## Notes

2025-01-14 20:03 UTC, ktyjscott requested changes
Posting a screenshot of the suggested changes along with the figma link:

<img width="490" alt="Screenshot 2025-01-14 at 12 11 08 PM" src="https://github.com/user-attachments/assets/cd5569bb-07c5-46a5-a5ed-37b3ee38f7f5" />

https://www.figma.com/design/jJIpEL3bBAHPFCHYoEPRzY/Platform-Components?node-id=828-20541&t=xWMBWQSCOyojdTBQ-1


1. Update community dropdown icon to utilize `chevrons-up-down`
2. Break up links into 3 distinct sections: 'Views', 'Manage', and 'Admin'. These should be styled at 12px, bold, all caps, with a color of slate-500
3. All Pubs now gets organized under 'Views', all active state colors should also be set to gray-200
4. 'All Workflows' gets added - should take the user to the stages page (https://app.pubpub.org/c/unjournal-demo/stages)
5. Under the 'Manage' section, links should be organized as shown in the designs, with the 'Workflows' link taking the user to the stage editor experience. Also make sure this link's icon is utilizing the `layers` icon
6. Settings receives a new icon: `settings-2`
7. Add new dropdown section for Docs
8. Utilize the new base 'User' segment as shown in the shadcn docs. I think this design with the menu helps clean up the options a lot, and i like how the icons are consistent with the community switcher up top

Please lmk if you have any questions or feedback on this that we may have overlooked :)

EDIT: I did in fact overlook the mobile version. I think the layout you have right now looks good - I would just say let's switch the icon to utilize `menu` as I think that will be a lot more recognizable/understandable to our users.

2025-01-21 15:27 UTC, tefkah commented on core/app/(user)/forgot/ForgotForm.tsx
> +		},
i added a number of these things in order to get rid of some errors, which were making tests fail in dev mode bc the error popup would overlap with the loginswitcher 😅

2025-01-21 15:27 UTC, tefkah commented on core/app/(user)/login/LoginForm.tsx
> +											<Input placeholder="name@example.com" {...field} />
about time we changed that, could also be `mail` probably

2025-01-21 15:28 UTC, tefkah commented on core/app/(user)/reset/ResetForm.tsx
>  						</DialogDescription>
`<DialogDescription>` already renders a `<p>`, so this was giving hydration errors bc you should not render `<p><p/></p>`

2025-01-21 21:28 UTC, 3mcd commented on core/app/c/[communitySlug]/NavLinkSubMenu.tsx
> +	}, [open]);
This effect is breaking my brain a bit. Shouldn't `mounted` always be `true` when the effect is called? What does setting it to `false` within the closure do?

2025-01-21 21:33 UTC, 3mcd approved these changes
Looks good. Just one question about a `useEffect` that I don't quite understand.

2025-01-23 11:26 UTC, tefkah commented on core/app/c/[communitySlug]/NavLinkSubMenu.tsx
> +	}, [open]);
ugh, sorry that comment took a while, i always accidentally add a "review" and then don't submit it 😅

2025-01-23 15:11 UTC, merged